# TCL File Generated by Component Editor 13.0sp1
# Mon Mar 14 22:02:21 GMT 2016
# DO NOT MODIFY


# 
# sum_vector "sum_vector" v1.0
#  2016.03.14.22:02:21
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module sum_vector
# 
set_module_property DESCRIPTION ""
set_module_property NAME sum_vector
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sum_vector
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pipeline
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file pipeline.vhd VHDL PATH pipeline.vhd TOP_LEVEL_FILE
add_fileset_file accumulator.vhd VHDL PATH fileOFaccum/accumulator.vhd
add_fileset_file fifo_cordic.vhd VHDL PATH fileOFaccum/fifo_cordic.vhd
add_fileset_file fpadd_en.vhd VHDL PATH fileOFaccum/fpadd_en.vhd
add_fileset_file fsm_adder.vhd VHDL PATH fileOFaccum/fsm_adder.vhd
add_fileset_file controller.vhd VHDL PATH fileOFreadmaster/controller.vhd
add_fileset_file fifo.v VERILOG PATH fileOFreadmaster/fifo.v
add_fileset_file latency_aware_read_master.v VERILOG PATH fileOFreadmaster/latency_aware_read_master.v
add_fileset_file memread.vhd VHDL PATH fileOFreadmaster/memread.vhd
add_fileset_file lsr7.vhd VHDL PATH fileOFaccum/lsr7.vhd
add_fileset_file lsr2.vhd VHDL PATH fileOFaccum/lsr2.vhd
add_fileset_file lsr26.vhd VHDL PATH fileOFaccum/lsr26.vhd
add_fileset_file lsr34.vhd VHDL PATH fileOFaccum/lsr34.vhd
add_fileset_file combined_func.vhd VHDL PATH fileOFcombinedfunc/combined_func.vhd
add_fileset_file cos_8.vhd VHDL PATH fileOFcombinedfunc/fileOFcosine/cos_8.vhd
add_fileset_file cos_rom.vhd VHDL PATH fileOFcombinedfunc/fileOFcosine/cos_rom.vhd
add_fileset_file cos_wrapper_8.vhd VHDL PATH fileOFcombinedfunc/fileOFcosine/cos_wrapper_8.vhd
add_fileset_file fpadd.vhd VHDL PATH fileOFcombinedfunc/fileOFcosine/fpadd.vhd
add_fileset_file fpmul.vhd VHDL PATH fileOFcombinedfunc/fileOFcosine/fpmul.vhd
add_fileset_file fx2fp.vhd VHDL PATH fileOFcombinedfunc/fileOFcosine/fx2fp.vhd
add_fileset_file slv_shift.vhdl VHDL PATH fileOFcombinedfunc/fileOFcosine/slv_shift.vhdl
add_fileset_file counter.vhd VHDL PATH fileOFtop/counter.vhd
add_fileset_file lsr32.vhd VHDL PATH fileOFaccum/lsr32.vhd
add_fileset_file fsm_finish.vhd VHDL PATH fsm_finish.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk_mm clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_mm reset Input 1


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave clk clk Output 1
add_interface_port nios_custom_instruction_slave reset reset Output 1
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave in_addr dataa Input 32
add_interface_port nios_custom_instruction_slave n_byte datab Input 32
add_interface_port nios_custom_instruction_slave result result Output 32


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_address address Output 32
add_interface_port avalon_master master_read read Output 1
add_interface_port avalon_master master_byteenable byteenable Output 4
add_interface_port avalon_master master_readdata readdata Input 32
add_interface_port avalon_master master_readdatavalid readdatavalid Input 1
add_interface_port avalon_master master_waitrequest waitrequest Input 1

